# Generated by Django 5.0 on 2023-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('ano_fabricacao', models.PositiveSmallIntegerField()),
                ('quant_passageiros', models.PositiveSmallIntegerField()),
                ('transmissao', models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático')], default='Manual', max_length=200, verbose_name='Câmbio')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Flex', 'Flex'), ('Elétrico', 'Elétrico')], default='Hibrido', max_length=200, verbose_name='Combustivel')),
                ('disponibilidade', models.CharField(choices=[('Disponivel', 'Disponivel'), ('Alugado', 'Alugado')], default='Disponivel', max_length=200, verbose_name='Status')),
                ('preco', models.PositiveIntegerField()),
            ],
        ),
    ]
