# Generated by Django 5.0 on 2023-12-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
