# Generated by Django 4.2.8 on 2023-12-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_carro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano_fabricacao',
            field=models.DateField(verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='disponibilidade',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Alugado', 'Alugado')], default='Disponivel', max_length=200, verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.PositiveIntegerField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='quant_passageiros',
            field=models.PositiveSmallIntegerField(verbose_name='Quantidade de Passageiros'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='transmissao',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático')], default='Manual', max_length=200, verbose_name='Transmissão'),
        ),
    ]
