# Generated by Django 4.2.8 on 2023-12-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_alter_carro_ano_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano_fabricacao',
            field=models.PositiveSmallIntegerField(verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.PositiveIntegerField(verbose_name='Preço do aluguel por dia'),
        ),
    ]
