# Generated by Django 4.2.8 on 2023-12-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_alter_carro_ano_fabricacao_alter_carro_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
